merge _bin/*.sh in to maintain script

diff --git a/maintain b/maintain
--- a/maintain
+++ b/maintain
@@ -1,10 +1,7 @@
 #!/bin/sh
 # Maintainer script for withlinux
+# COPYRIGHT (C) 2016 Lumin Zhou, MIT License
 set -e
-
-lines=$(sh _bin/stat_lines.sh | tail -n1 | awk '{print $1}' | sed -e 's/\n//g')
-files=$(find . -path ./.git -prune -o -name '*.pdf' -prune -o -type f -print | nl | tail -n1 | awk '{print $1}' | sed -e 's/\n//g')
-sizes=$(du -sh . | awk '{print $1}' | sed -e 's/\n//g')
 
 Usage () {
 printf "%s" "[m"
@@ -20,24 +17,52 @@ printf "Project withlinux has %s%d%s lines currently.\n" "[33;1m" $lines "[;0m
 printf "Project withlinux occupies %s%s%s of disk space.\n" "[36;1m" $sizes "[;0m"
 }
 
-# detect arg
-if [ -z $1 ]; then
-  Usage
-  exit 1
-fi
+scan_missing () {
+  local SCAN="README.md"
+  local FILES="$(find . | grep -v '.git')"
+  
+  for ITEM in ${FILES}; do
+    if [ -f ${ITEM} ]; then
+      if ! grep "${ITEM})" ${SCAN} 2>&1 1>/dev/null; then
+        printf "[%s] is missing in [%s].\n" ${ITEM} ${SCAN}
+      fi
+    else
+      #printf "%s is not a regular file, skip...\n" ${ITEM}
+  	continue
+    fi
+  done
+}
 
-# invoke sub scripts
-case $1 in
-scan)
-  exec _bin/scan_missing.sh
-  ;;
-stat)
-  exec _bin/stat_lines.sh
-  ;;
-help)
-  Usage
-  ;;
-*)
-  echo "E: invalid action"
-  ;;
-esac
+stat_lines () {
+  find . -path ./.git -prune -o -name '*.pdf' -prune -o -type f -exec cat -n {} +
+}
+
+# get some data first 
+lines=$(stat_lines | tail -n1 | awk '{print $1}' | sed -e 's/\n//g')
+files=$(find . -path ./.git -prune -o -name '*.pdf' -prune -o -type f -print | nl | tail -n1 | awk '{print $1}' | sed -e 's/\n//g')
+sizes=$(du -sh . | awk '{print $1}' | sed -e 's/\n//g')
+
+main () {
+  # detect arg
+  if [ -z $1 ]; then
+    Usage
+    exit 1
+  fi
+  
+  # invoke sub scripts
+  case $1 in
+  scan)
+    scan_missing
+    ;;
+  stat)
+    stat_lines
+    ;;
+  help)
+    Usage
+    ;;
+  *)
+    echo "E: invalid action"
+    ;;
+  esac
+}
+main $@
